name: Run Compile

on:
  workflow_call:
  workflow_dispatch:
  pull_request:
  merge_group:
  workflow_run:
    workflows: [ "Run Clang-Format and Clang-Tidy" ]
    types:
      - completed

permissions:
  contents: write

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]
        compiler: [ gcc, clang ]
        arch: [
          ${{ (matrix.os == 'macos-latest') && 'x86_64' || 'x86_64' }},
          ${{ (matrix.os == 'macos-latest') && 'arm64' || 'arm64' }},
          ${{ (matrix.os == 'macos-latest') && 'aarch64' || 'aarch64' }},
          ${{ (matrix.os == 'ubuntu-latest') && 'riscv64' || '' }}
        ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Set up QEMU for cross-arch (Linux only)
        if: matrix.os == 'ubuntu-latest' && matrix.arch != 'x86_64'
        uses: docker/setup-qemu-action@v3

      - name: Install dependencies on Linux
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt update && sudo apt install -y cmake g++ make libboost-all-dev libicu-dev qemu-user-static

      - name: Install dependencies on macOS
        if: matrix.os == 'macos-latest'
        run: brew install gcc boost icu4c && brew link --force icu4c

      - name: Initialize git submodules
        run: |
          git submodule update --init --recursive
          git submodule foreach git pull origin main

      - name: Run CMake
        run: |
          cmake .
          make -j$(getconf _NPROCESSORS_ONLN)

      - name: Test the built executable
        run: |
          echo "console.log('Everything works fine!');" > test.js
          ./js_cmp test.js
          diff <(./test) <(echo "Everything works fine!")

      - name: Check built binary architecture
        run: |
          if [[ "${{ matrix.os }}" == "ubuntu-latest" ]]; then
            file ./js_cmp
          else
            file ./js_cmp
            lipo -info ./js_cmp || true
          fi
