jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        compiler: [gcc, clang]

    steps:
      # Étape 1 : Cloner le dépôt
      - name: Checkout repository
        uses: actions/checkout@v3

      # Étape 2 : Installer les dépendances pour Linux et macOS
      - name: Install dependencies on Linux
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get update && sudo apt-get install -y cmake g++ make

      - name: Install dependencies on macOS
        if: matrix.os == 'macos-latest'
        run: brew install cmake gcc

      # Étape 3 : Créer les répertoires de build et compiler
      - name: Create build directory
        run: mkdir -p build

      - name: Run CMake
        run: |
          cd build
          cmake ..
          make
        continue-on-error: true  # Ajouter cette ligne pour que le job continue même en cas d'erreur

      # Étape 4 : Tester l'exécutable généré
      - name: Test the built executable
        run: |
          cd build
          ./JS_CMP_alpha
