name: Run Compile

on:
  workflow_call:
  workflow_dispatch:
  pull_request:
  merge_group:
  push:
    branches:
      - 'features/action-compile'

permissions:
  contents: write

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        compiler: [gcc, clang]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Install dependencies on Linux
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get update && sudo apt-get install -y cmake g++ make libboost-all-dev

      - name: Install dependencies on macOS
        if: matrix.os == 'macos-latest'
        run: brew install cmake gcc boost

      - name: Initialize git submodules
        run: git submodule update --init --recursive

      - name: Run CMake
        run: |
          cmake .
          make -j$(getconf _NPROCESSORS_ONLN)

      - name: Test the built executable
        run: |
          echo "console.log('Everything works fine!');" > test.js
          ./js_cmp test.js
          diff <(./test) <(echo "Everything works fine!")