name: Run Clang-Format and Clang-Tidy

on:
  workflow_call:
  workflow_dispatch:
  pull_request:
  merge_group:

permissions:
  contents: write

jobs:
  clang:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Install clang-format, git, and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-format git

      # Install clang-tidy and git
      - name: Install Clang-Tidy, git, and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-tidy git libboost-all-dev

      # Run clang-tidy on the codebase
      - name: Run Clang-Tidy
        run: |
          git submodule update --init --recursive
          cmake . -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
          jq 'map(select(.file | test("submodules") | not))' ./build/compile_commands.json > ./build/new_compile_commands.json && mv ./build/new_compile_commands.json build/compile_commands.json
          run-clang-tidy -fix -quiet

      # Run clang-format on the codebase
      - name: Run clang-format
        run: |
          git ls-files '*.cpp' '*.hpp' | xargs clang-format -i      

        # Check if there are any changes after running clang-format
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Formating Clang-Format and Clang-Tidy"

