name: Uncrustify and Cpplint

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  format_and_lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Étape 1 : Installer les dépendances nécessaires pour compiler Uncrustify
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y git cmake g++ make

      # Étape 2 : Cloner et compiler Uncrustify à partir du dépôt source
      - name: Install latest Uncrustify from source
        run: |
          git clone https://github.com/uncrustify/uncrustify.git
          cd uncrustify
          mkdir build && cd build
          cmake ..
          make -j$(nproc)
          sudo make install

      # Étape 3 : Exécuter Uncrustify
      - name: Run Uncrustify
        run: |
          uncrustify -c uncrustify/uncrustify.cfg --replace $(find . -name "*.cpp" -o -name "*.h")

      # Étape 4 : Installer Cpplint
      - name: Install Cpplint
        run: sudo pip install cpplint

      # Étape 5 : Exécuter Cpplint
      - name: Run Cpplint
        run: cpplint $(find . -name "*.cpp" -o -name "*.h")
