name: Mirror Repository to Epitech

on: [push, delete]

jobs:
  to_epitech_repo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            git@github.com:EpitechPromo2026/G-EIP-700-lil-7-1-eip-simon.bandiera.git
          ssh_private_key:
            ${{ secrets.GIT_SSH_PRIVATE_KEY }}
