name: Mirror Repository to Epitech

on: [ push, delete, create ]

concurrency:
  group: git-mirror-me

jobs:
  git-mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: yesolutions/mirror-action@master
        with:
          REMOTE: git@github.com:EpitechPromo2026/G-EIP-700-lil-7-1-eip-simon.bandiera.git
          GIT_SSH_PRIVATE_KEY: ${{ secrets.GMM_SSH_PRIVATE_KEY }}
          GIT_SSH_NO_VERIFY_HOST: "true"